import random

def generate_post_script():
    # AI bilan generatsiya qilishga urinib ko'ramiz
    try:
        from ai_generator import generate_super_post
        ai_result, img_prompt = generate_super_post()
        if ai_result:
            return ai_result, img_prompt
    except Exception as e:
        print(f"AI generatsiyasida xato, zaxiraga o'tilmoqda: {e}")
    
    # Agar AI ishlamasa, zaxiradagi oflayn format
    default_image_prompt = "A dramatic anti-doping motivational poster, cinematic lighting, highly detailed, professional sport"
    
    topics = [
        "❓ Savol: Musobaqadan oldin qattiq shamollab qoldim. Aptekadan oddiy 'Teraflyu' yoki 'Taylolxot' kabi dorilarni sotib olib ichsam bo'ladimi?\n\n✅ Javobi: Qat'iyan ehtiyot bo'ling! Bunday keng tarqalgan kompleks dori vositalari tarkibida ko'pincha 'Efedrin' yoki 'Psevdoefedrin' kabi kuchli stimulyatorlar mavjud bo'lib, ular musobaqa davrida qat'iyan taqiqlangan dorilar ro'yxatiga kiradi. Oqibati — darhol diskvalifikatsiya! Har doim dorini qabul qilishdan oldin GlobalDRO.com xalqaro bazasi orqali uning tarkibini tekshiring yoki faqat jamoa shifokori ruxsat bergan oddiy Paratsetamol/Ibuprofen qabul qiling.",
        "❓ Savol: Men xorijdan qimmat va sifatli sport oziq-ovqati (Protin, BCAA, Kreatin) sotib oldim. Lekin uning tozaligiga (doping yo'qligiga) qanday qilib yuz foiz ishonch hosil qilishim mumkin?\n\n✅ Javobi: Eng yaxshi va ishonchli himoya — bu qutida 'Informed-Sport' yoki 'NSF Certified for Sport' logotiplarini qidirishdir. Bu xalqaro sertifikatlar har bir partiya mustaqil laboratoriyada xavfli moddalarga tekshirilganini kafolatlaydi. Shunga qaramay, WADA ning 'Qat'iy javobgarlik' qoidasiga ko'ra, tavakkalchilik va javobgarlik baribir o'zingizning bo'yningizda qoladi.",
        "❓ Savol: Doping-ofitser (DCO) mendan test olishga keldi, lekin men ingliz yoki rus tilini umuman tushunmayman. Bunday vaziyatda qanday huquqlarim bor?\n\n✅ Javobi: Vahimaga tushmang va qochishga urinmang! Siz ofitserdan jarayonni to'liq tushunish uchun tarjimon yoki o'z vakilingizni (murabbiy, shifokor) chaqirishni talab qilish huquqiga egasiz. Garchi DCO sizni uzoq kutishga majbur bo'lmasa-da, siz bu huquqingiz poymol bo'lganini Doping nazorati bayonnomasining 'Izohlar' (Comments) qismiga o'z ona tilingizda yozib qo'yishingiz shart.",
        "❓ Savol: Boks, dzyudo yoki kurash kabi yakkakurashlarda vazn tashlash (ves quvish) maqsadida 'Furosemid' kabi siydik haydovchi dorilar ichilsa qanday chora ko'riladi?\n\n✅ Javobi: Bu zamonaviy sportdagi eng og'ir jinoyatlardan biri hisoblanadi! Diuretiklar (Furosemid, Torasemid) sportchiga hech qanday kuch bermaydi, lekin ular organizmdagi boshqa og'ir doping moddalarining (masalan, steroidlarning) izini siydik bilan tez yuvib yuboruvchi 'Niqoblovchi agent' (Masking agent) vazifasini bajaradi. Aniqlansa, hech qanday uzrsiz 4 yilgacha qat'iy diskvalifikatsiya olasiz.",
        "❓ Savol: Menga doim dorilarni va ozuqaviy vitaminlarni shaxsiy murabbiyim beradi. Agar ertaga tahlilimdan doping chiqib qolsa, murabbiyimni ayblab o'zim jazodan qutula olamanmi?\n\n✅ Javobi: Mutlaqo yo'q! WADA'ning qat'iy va shafqatsiz 'Strict Liability' (Qat'iy javobgarlik) qoidasiga ko'ra, sportchining tanasiga kirgan har bir tomchi dori uchun yuz foiz sportchining shaxsan o'zi javobgar. Murabbiy yoki shifokor ham jinoiy jazolanishi mumkin, lekin bu fakt sizni diskvalifikatsiyadan oqlamaydi. O'zingiz ichayotgan har bir dorining tarkibini so'rashga majbursiz!",
        "❓ Savol: Astma (nafas qisishi) kasalligim bor. Nafas olishni yengillashtiruvchi Ingalatorlar (masalan, Salbutamol) sportda doping hisoblanadimi?\n\n✅ Javobi: Salbutamol kabi preparatlar faqatgina ruxsat etilgan me'yor doirasida (12 soat ichida maksimal 800 mikrogrammgacha) ishlatilishi mumkin. Biroq, agar sizga undan kuchliroq preparat zarur bo'lsa, musobaqadan kamida bir oy oldin 'Terapevtik Istisno' (TUE) hujjati to'ldirilib, maxsus tibbiy komissiyaga yuborilishi va tasdiqlanishi shart.",
        "❓ Savol: Qon testini topshirishdan qochish uchun 'Ignadan qo'rqish' (Belonefobiya) yoki ruhiy siqilish kasalligimni ro'kach qilsam, ofitser meni kechiradimi?\n\n✅ Javobi: Afsuski, yo'q. Doping tahlilini topshirishdan bosh tortish yoki undan qochish — to'g'ridan-to'g'ri musbat natija bilan tenglashtiriladi va 4 yillik chetlatishga olib keladi. Hatto o'ta og'ir rasmiy ruhiy kasallik tashxisingiz bo'lsa ham, bu sizni qon topshirish majburiyatidan ozod qilmaydi.",
        "❓ Savol: Kutilmagan avariya yoki jarohat sababli tezyordam xizmati menga hayotimni saqlab qolish uchun kuchli og'riq qoldiruvchi (Narkotik) ukol qildi. Karyeram nima bo'ladi?\n\n✅ Javobi: Bunday shoshilinch favqulodda hollarda inson hayoti va sog'lig'i birinchi o'rinda turadi! Muolajani to'liq oling. Hayot xavfdan o'tgan zahoti jamoa shifokori darhol 'Ortga qaytuvchi TUE' (Retroactive TUE) ga ariza topshirishi kerak. Kasalxona qog'ozlari isbotlansa, WADA buni inobatga oladi.",
        "❓ Savol: Musobaqa tugashi bilan doping ofitseri menga yaqinlashdi, lekin men o'ta terlaganman, darhol yuvinishim va kiyim almashtirishim kerak. Ruxsat bormi?\n\n✅ Javobi: Bunga faqatgina DCO (Doping-ofitser) ning bevosita va qat'iy kuzatuvi ostidagina ruxsat beriladi! Sizga bildirishnoma berilgan soniyadan boshlab toki sinov to'liq tugaguniga qadar DCO sizni ko'zdan qochirmasligi shart. Ruxsatsiz dushga kirish — firibgarlik deb baholanadi.",
        "❓ Savol: Internetdan buyurtma qilingan '100% tabiiy' o'simlik choylari va dorivor giyohlar doping testida musbat natija ko'rsatishi mumkinmi?\n\n✅ Javobi: Bunga juda katta xavf bor! Bozorlardagi ko'plab 'Tabiiy energiya beruvchi' giyohlar tarkibida tabiiy Efedrin (Mahuang) kabi taqiqlangan alkaloidlar yashirin mavjud bo'ladi. 'Tabiiy' degani 'Sportda ruxsat etilgan' degani emas! Doimo hushyor bo'ling va yorliqlarni mutaxassis bilan tekshiring.",
        "❓ Savol: O'yin davomida kuchli charchoqni olish uchun har kuni 5-6 banka Energetik ichimlik (RedBull, Gorilla) ichaman. Bu qoidabuzarlikka kiradimi?\n\n✅ Javobi: Kofein 2004-yildan beri WADA ning taqiqlangan ro'yxatidan rasman chiqarilgan. Biroq, u hanuzgacha 'Kuzatuv dasturi'da turibdi. Qolaversa, ba'zi arzon xalqaro energetiklar tarkibida Geran (DMAA) kabi yashirin taqiqlangan xatarli moddalar ham tez-tez uchrashi kuzatilgan.",
        "❓ Savol: Tizza bo'g'imlarimni davolash uchun shifokor to'g'ridan-to'g'ri bo'g'im ichiga (Diprospan) inyeksiya yozib berdi. Nima qilishim kerak?\n\n✅ Javobi: 2022-yilgi WADA qoidalariga ko'ra, barcha turdagi Glukokortikoid inyeksiyalari musobaqa davrida qat'iyan taqiqlangan! Agar musobaqagacha davolanish (Washout period) muddati yetarli bo'lmasa, siz albatta TUE olishingiz shart, aks holda tahlilingiz albatta musbat chiqadi.",
        "❓ Savol: Menda 'A proba' musbat chiqdi va meni darhol chetlatishdi. Lekin men 100% o'zimga ishonaman! Endi huquqlarim qanday bo'ladi?\n\n✅ Javobi: Hech qachon umidsizlikka tushmang. Sizda o'z hisobingizdan 7 kun ichida mustaqil 'B proba'ni ochishni talab qilishdek fundamental huquq bor. Shuningdek, o'z yuridik vakilingiz bilan o'sha xorijdagi laboratoriyaga borib, kolba qay tarzda ochilayotganini shaxsan kuzatib turishingiz mumkin.",
        "❓ Savol: Xorijga uzoq yig'inga (sbor) ketyapmiz. ADAMS tizimiga yangi manzilni kiritish esdan chiqibdi. Eng yomoni nima bo'lishi mumkin?\n\n✅ Javobi: Agar kutilmagan doping-inspektor sizni ADAMS da ko'rsatilgan oldingi manzildan topa olmasa, bu 'Filing failure' (Manzilni kiritmaslik) hisoblanadi. Agar 12 oy ichida bunday jiddiy xato 3 marta takrorlansa, siz hech qanday dopingsiz ham 1 yildan 2 yilgacha sportdan sharmandali chetlatilasiz!",
        "❓ Savol: 8 yil oldingi Olimpiadada oltin medal yutgan edim, hozir hammasi joyida, endi butunlay xotirjam bo'lsam bo'ladimi?\n\n✅ Javobi: Aslo unday emas! WADA sizning qon va siydik namunalaringizni eng zamonaviy laboratoriya muzlatgichlarida naq 10 yilgacha saqlaydi. Texnologiyalar rivojlangani sari, eski namunalar mutlaqo yangi usullarda qayta tahlil qilinadi (Re-analysis). Vaqt o'tib firibgarlik aniqlansa, barcha medallar tortib olinadi."
    ]
    chosen = random.choice(topics)
    
    selected_topic = f"🎙 Doping va Sport qoidalari bo'yicha Maxsus Podkast!\n\n{chosen}\n\n⚠️ Eslatma: Doping qoidalari tez-tez o'zgarib turadi. Har doim yangiliklarni kuzatib boring va mutaxassislar bilan maslahatlashing. Barchangizga sog'lom va halol sport tilaymiz!"
    
    return selected_topic, default_image_prompt

if __name__ == "__main__":
    post, img = generate_post_script()
    print("YANGILIK POSTI:\n\n", post)
