name: Generate Video Podcast

on:
  repository_dispatch:
    types: [trigger_video]
  workflow_dispatch: # Imkoniyat bo'lishi uchun qoldirdik (manual ishlatishga)

jobs:
  generate_and_send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run GitHub Worker
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          DEEPSEEK_KEY: ${{ secrets.DEEPSEEK_KEY }}
        run: |
          python github_worker.py
